<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CoreCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('core_city')->insert([
            ['city_id' => 936, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Gianyar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 937, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Bangli', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 938, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Buleleng', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 939, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Tabanan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 940, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Karangasem', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 941, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Badung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 942, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Jembrana', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 943, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Klungkung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 944, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kota Denpasar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 945, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Bangka Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 946, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Bangka Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 947, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Belitung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 948, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kota Pangkal Pinang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 949, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Bangka Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 950, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Bangka', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 951, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Belitung Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 952, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kabupaten Lebak', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 953, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kabupaten Serang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 954, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kota Serang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 955, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kabupaten Tangerang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 956, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kota Tangerang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 957, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kabupaten Pandeglang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 958, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kota Tangerang Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 959, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kota Cilegon', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 960, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Seluma', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 961, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Bengkulu Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 962, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kota Bengkulu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 963, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Muko Muko', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 964, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Rejang Lebong', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 965, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Kaur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 966, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Bengkulu Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 967, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Kepahiang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 968, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Lebong', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 969, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Bengkulu Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 970, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kabupaten Gunung Kidul', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 971, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kota Yogyakarta', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 972, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kabupaten Kulon Progo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 973, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kabupaten Sleman', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 974, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kabupaten Bantul', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 975, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 976, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 977, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Pusat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 978, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 979, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 980, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kabupaten Kepulauan Seribu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 981, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Boalemo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 982, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Pohuwato', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 983, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Gorontalo Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 984, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Gorontalo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 985, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Bone Bolango', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 986, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kota Gorontalo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 987, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Tebo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 988, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Tanjung Jabung Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 989, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Merangin', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 990, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kota Jambi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 991, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Bungo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 992, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kota Sungaipenuh', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 993, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Muaro Jambi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 994, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Kerinci', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 995, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Sarolangun', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 996, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Tanjung Jabung Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 997, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Batang Hari', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 998, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Indramayu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 999, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Cirebon', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1000, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Cianjur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1001, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Sukabumi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1002, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Sukabumi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1003, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Purwakarta', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1004, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Garut', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1005, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Sumedang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1006, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Bandung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1007, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Karawang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1008, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Bogor', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1009, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Tasikmalaya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1010, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Bekasi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1011, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Tasikmalaya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1012, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Depok', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1013, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Subang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1014, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Bogor', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1015, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Ciamis', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1016, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Majalengka', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1017, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Kuningan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1018, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Bandung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1019, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Bandung Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1020, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Pangandaran', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1021, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Bekasi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1022, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Banjar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1023, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Cirebon', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1024, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Cimahi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1025, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Wonogiri', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1026, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Batang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1027, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Wonosobo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1028, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Boyolali', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1029, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Klaten', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1030, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Demak', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1031, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Pekalongan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1032, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Temanggung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1033, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Grobogan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1034, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Pati', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1035, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Magelang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1036, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Sukoharjo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1037, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Kendal', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1038, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Jepara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1039, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Pemalang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1040, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Tegal', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1041, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Banyumas', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1042, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Banjarnegara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1043, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Brebes', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1044, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Cilacap', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1045, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Semarang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1046, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Kudus', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1047, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Blora', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1048, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Semarang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1049, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Salatiga', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1050, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Tegal', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1051, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Karanganyar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1052, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Sragen', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1053, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Rembang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1054, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Kebumen', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1055, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Surakarta', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1056, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Purbalingga', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1057, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Purworejo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1058, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Pekalongan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1059, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Magelang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1060, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Bangkalan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1061, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Banyuwangi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1062, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Batu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1063, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Blitar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1064, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Blitar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1065, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Bojonegoro', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1066, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Bondowoso', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1067, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Gresik', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1068, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Jember', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1069, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Jombang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1070, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Kediri', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1071, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Kediri', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1072, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Lamongan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1073, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Lumajang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1074, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Madiun', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1075, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Madiun', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1076, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Magetan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1077, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Malang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1078, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Malang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1079, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Mojokerto', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1080, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Mojokerto', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1081, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Nganjuk', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1082, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Ngawi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1083, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Pacitan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1084, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Pamekasan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1085, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Pasuruan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1086, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Pasuruan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1087, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Ponorogo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1088, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Probolinggo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1089, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Probolinggo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1090, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Sampang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1091, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Sidoarjo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1092, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Situbondo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1093, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Sumenep', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1094, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Surabaya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1095, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Trenggalek', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1096, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Tuban', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1097, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Tulungagung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1098, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Bengkayang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1099, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Kapuas Hulu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1100, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Kayong Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1101, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Ketapang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1102, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Kubu Raya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1103, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Landak', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1104, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Melawi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1105, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Mempawah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1106, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kota Pontianak', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1107, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Sambas', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1108, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Sanggau', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1109, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Sekadau', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1110, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kota Singkawang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1111, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Sintang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1112, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Balangan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1113, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Banjar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1114, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kota Banjarbaru', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1115, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kota Banjarmasin', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1116, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Barito Kuala', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1117, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Hulu Sungai Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1118, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Hulu Sungai Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1119, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Hulu Sungai Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1120, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Kotabaru', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1121, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Tabalong', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1122, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Tanah Bumbu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1123, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Tanah Laut', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1124, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Tapin', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1125, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Barito Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1126, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Barito Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1127, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Barito Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1128, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Gunung Mas', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1129, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Kapuas', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1130, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Katingan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1131, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Kotawaringin Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1132, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Kotawaringin Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1133, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Lamandau', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1134, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Murung Raya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1135, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kota Palangka Raya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1136, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Pulang Pisau', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1137, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Seruyan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1138, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Sukamara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1139, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kota Balikpapan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1140, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kabupaten Berau', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1141, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kota Bontang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1142, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kabupaten Kutai Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1143, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kabupaten Kutai Kartanegara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1144, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kabupaten Kutai Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1145, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kabupaten Mahakam Ulu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1146, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kabupaten Paser', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1147, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kabupaten Penajam Paser Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1148, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kota Samarinda', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1149, 'city_code' => '', 'province_id' => '77', 'province_code' => '', 'city_name' => 'Kabupaten Bulungan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1150, 'city_code' => '', 'province_id' => '77', 'province_code' => '', 'city_name' => 'Kabupaten Malinau', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1151, 'city_code' => '', 'province_id' => '77', 'province_code' => '', 'city_name' => 'Kabupaten Nunukan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1152, 'city_code' => '', 'province_id' => '77', 'province_code' => '', 'city_name' => 'Kabupaten Tana Tidung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1153, 'city_code' => '', 'province_id' => '77', 'province_code' => '', 'city_name' => 'Kota Tarakan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1154, 'city_code' => '', 'province_id' => '78', 'province_code' => '', 'city_name' => 'Kota Batam', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1155, 'city_code' => '', 'province_id' => '78', 'province_code' => '', 'city_name' => 'Kabupaten Bintan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1156, 'city_code' => '', 'province_id' => '78', 'province_code' => '', 'city_name' => 'Kabupaten Karimun', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1157, 'city_code' => '', 'province_id' => '78', 'province_code' => '', 'city_name' => 'Kabupaten Kepulauan Anambas', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1158, 'city_code' => '', 'province_id' => '78', 'province_code' => '', 'city_name' => 'Kabupaten Lingga', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1159, 'city_code' => '', 'province_id' => '78', 'province_code' => '', 'city_name' => 'Kabupaten Natuna', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1160, 'city_code' => '', 'province_id' => '78', 'province_code' => '', 'city_name' => 'Kota Tanjung Pinang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1161, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kota Bandar Lampung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1162, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kabupaten Lampung Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1163, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kabupaten Lampung Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1164, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kabupaten Lampung Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1165, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kabupaten Lampung Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1166, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kabupaten Lampung Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1167, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kabupaten Mesuji', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1168, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kota Metro', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1169, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kabupaten Pesawaran', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1170, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kabupaten Pesisir Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1171, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kabupaten Pringsewu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1172, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kabupaten Tanggamus', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1173, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kabupaten Tulang Bawang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1174, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kabupaten Tulang Bawang Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1175, 'city_code' => '', 'province_id' => '79', 'province_code' => '', 'city_name' => 'Kabupaten Way Kanan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1176, 'city_code' => '', 'province_id' => '80', 'province_code' => '', 'city_name' => 'Kota Ambon', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1177, 'city_code' => '', 'province_id' => '80', 'province_code' => '', 'city_name' => 'Kabupaten Buru', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1178, 'city_code' => '', 'province_id' => '80', 'province_code' => '', 'city_name' => 'Kabupaten Buru Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1179, 'city_code' => '', 'province_id' => '80', 'province_code' => '', 'city_name' => 'Kabupaten Kepulauan Aru', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1180, 'city_code' => '', 'province_id' => '80', 'province_code' => '', 'city_name' => 'Kabupaten Maluku Barat Daya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1181, 'city_code' => '', 'province_id' => '80', 'province_code' => '', 'city_name' => 'Kabupaten Maluku Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1182, 'city_code' => '', 'province_id' => '80', 'province_code' => '', 'city_name' => 'Kabupaten Maluku Tenggara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1183, 'city_code' => '', 'province_id' => '80', 'province_code' => '', 'city_name' => 'Kabupaten Maluku Tenggara Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1184, 'city_code' => '', 'province_id' => '80', 'province_code' => '', 'city_name' => 'Kabupaten Seram Bagian Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1185, 'city_code' => '', 'province_id' => '80', 'province_code' => '', 'city_name' => 'Kabupaten Seram Bagian Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1186, 'city_code' => '', 'province_id' => '80', 'province_code' => '', 'city_name' => 'Kota Tual', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1187, 'city_code' => '', 'province_id' => '81', 'province_code' => '', 'city_name' => 'Kabupaten Halmahera Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1188, 'city_code' => '', 'province_id' => '81', 'province_code' => '', 'city_name' => 'Kabupaten Halmahera Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1189, 'city_code' => '', 'province_id' => '81', 'province_code' => '', 'city_name' => 'Kabupaten Halmahera Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1190, 'city_code' => '', 'province_id' => '81', 'province_code' => '', 'city_name' => 'Kabupaten Halmahera Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1191, 'city_code' => '', 'province_id' => '81', 'province_code' => '', 'city_name' => 'Kabupaten Halmahera Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1192, 'city_code' => '', 'province_id' => '81', 'province_code' => '', 'city_name' => 'Kabupaten Kepulauan Sula', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1193, 'city_code' => '', 'province_id' => '81', 'province_code' => '', 'city_name' => 'Kabupaten Pulau Morotai', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1194, 'city_code' => '', 'province_id' => '81', 'province_code' => '', 'city_name' => 'Kabupaten Pulau Taliabu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1195, 'city_code' => '', 'province_id' => '81', 'province_code' => '', 'city_name' => 'Kota Ternate', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1196, 'city_code' => '', 'province_id' => '81', 'province_code' => '', 'city_name' => 'Kota Tidore Kepulauan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1197, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Aceh Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1198, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Aceh Barat Daya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1199, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Aceh Besar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1200, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Aceh Jaya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1201, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Aceh Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1202, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Aceh Singkil', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1203, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Aceh Tamiang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1204, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Aceh Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1205, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Aceh Tenggara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1206, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Aceh Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1207, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Aceh Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1208, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kota Banda Aceh', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1209, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Bener Meriah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1210, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Bireuen', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1211, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Gayo Lues', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1212, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kota Lhokseumawe', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1213, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Nagan Raya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1214, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Pidie', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1215, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Pidie Jaya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1216, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kota Sabang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1217, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kabupaten Simeulue', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1218, 'city_code' => '', 'province_id' => '82', 'province_code' => '', 'city_name' => 'Kota Subulussalam', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1219, 'city_code' => '', 'province_id' => '83', 'province_code' => '', 'city_name' => 'Kota Bima', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1220, 'city_code' => '', 'province_id' => '83', 'province_code' => '', 'city_name' => 'Kabupaten Bima', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1221, 'city_code' => '', 'province_id' => '83', 'province_code' => '', 'city_name' => 'Kabupaten Dompu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1222, 'city_code' => '', 'province_id' => '83', 'province_code' => '', 'city_name' => 'Kabupaten Lombok Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1223, 'city_code' => '', 'province_id' => '83', 'province_code' => '', 'city_name' => 'Kabupaten Lombok Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1224, 'city_code' => '', 'province_id' => '83', 'province_code' => '', 'city_name' => 'Kabupaten Lombok Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1225, 'city_code' => '', 'province_id' => '83', 'province_code' => '', 'city_name' => 'Kabupaten Lombok Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1226, 'city_code' => '', 'province_id' => '83', 'province_code' => '', 'city_name' => 'Kota Mataram', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1227, 'city_code' => '', 'province_id' => '83', 'province_code' => '', 'city_name' => 'Kabupaten Sumbawa', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1228, 'city_code' => '', 'province_id' => '83', 'province_code' => '', 'city_name' => 'Kabupaten Sumbawa Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1229, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Alor', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1230, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Belu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1231, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Ende', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1232, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Flores Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1233, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kota Kupang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1234, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Kupang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1235, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Lembata', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1236, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Malaka', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1237, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Manggarai', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1238, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Manggarai Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1239, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Manggarai Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1240, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Nagekeo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1241, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Ngada', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1242, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Rote Ndao', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1243, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Sabu Raijua', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1244, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Sikka', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1245, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Sumba Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1246, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Sumba Barat Daya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1247, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Sumba Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1248, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Sumba Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1249, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Timor Tengah Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1250, 'city_code' => '', 'province_id' => '84', 'province_code' => '', 'city_name' => 'Kabupaten Timor Tengah Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1251, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Asmat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1252, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Biak Numfor', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1253, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Boven Digoel', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1254, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Deiyai', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1255, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Dogiyai', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1256, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Intan Jaya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1257, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kota Jayapura', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1258, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Jayapura', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1259, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Jayawijaya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1260, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Keerom', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1261, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Kepulauan Yapen', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1262, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Lanny Jaya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1263, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Mamberamo Raya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1264, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Mamberamo Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1265, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Mappi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1266, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Merauke', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1267, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Mimika', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1268, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Nabire', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1269, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Nduga', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1270, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Paniai', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1271, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Pegunungan Bintang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1272, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Puncak', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1273, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Puncak Jaya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1274, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Sarmi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1275, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Supiori', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1276, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Tolikara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1277, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Waropen', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1278, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Yahukimo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1279, 'city_code' => '', 'province_id' => '85', 'province_code' => '', 'city_name' => 'Kabupaten Yalimo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1280, 'city_code' => '', 'province_id' => '86', 'province_code' => '', 'city_name' => 'Kabupaten Fakfak', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1281, 'city_code' => '', 'province_id' => '86', 'province_code' => '', 'city_name' => 'Kabupaten Kaimana', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1282, 'city_code' => '', 'province_id' => '86', 'province_code' => '', 'city_name' => 'Kabupaten Manokwari', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1283, 'city_code' => '', 'province_id' => '86', 'province_code' => '', 'city_name' => 'Kabupaten Manokwari Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1284, 'city_code' => '', 'province_id' => '86', 'province_code' => '', 'city_name' => 'Kabupaten Maybrat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1285, 'city_code' => '', 'province_id' => '86', 'province_code' => '', 'city_name' => 'Kabupaten Pegunungan Arfak', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1286, 'city_code' => '', 'province_id' => '86', 'province_code' => '', 'city_name' => 'Kabupaten Raja Ampat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1287, 'city_code' => '', 'province_id' => '86', 'province_code' => '', 'city_name' => 'Kota Sorong', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1289, 'city_code' => '', 'province_id' => '86', 'province_code' => '', 'city_name' => 'Kabupaten Sorong Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1290, 'city_code' => '', 'province_id' => '86', 'province_code' => '', 'city_name' => 'Kabupaten Tambrauw', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1291, 'city_code' => '', 'province_id' => '86', 'province_code' => '', 'city_name' => 'Kabupaten Teluk Bintuni', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1292, 'city_code' => '', 'province_id' => '86', 'province_code' => '', 'city_name' => 'Kabupaten Teluk Wondama', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1293, 'city_code' => '', 'province_id' => '87', 'province_code' => '', 'city_name' => 'Kabupaten Bengkalis', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1294, 'city_code' => '', 'province_id' => '87', 'province_code' => '', 'city_name' => 'Kota Dumai', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1295, 'city_code' => '', 'province_id' => '87', 'province_code' => '', 'city_name' => 'Kabupaten Indragiri Hilir', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1296, 'city_code' => '', 'province_id' => '87', 'province_code' => '', 'city_name' => 'Kabupaten Indragiri Hulu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1297, 'city_code' => '', 'province_id' => '87', 'province_code' => '', 'city_name' => 'Kabupaten Kampar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1298, 'city_code' => '', 'province_id' => '87', 'province_code' => '', 'city_name' => 'Kabupaten Kepulauan Meranti', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1299, 'city_code' => '', 'province_id' => '87', 'province_code' => '', 'city_name' => 'Kabupaten Kuantan Singingi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1300, 'city_code' => '', 'province_id' => '87', 'province_code' => '', 'city_name' => 'Kota Pekanbaru', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1301, 'city_code' => '', 'province_id' => '87', 'province_code' => '', 'city_name' => 'Kabupaten Pelalawan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1302, 'city_code' => '', 'province_id' => '87', 'province_code' => '', 'city_name' => 'Kabupaten Rokan Hilir', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1303, 'city_code' => '', 'province_id' => '87', 'province_code' => '', 'city_name' => 'Kabupaten Rokan Hulu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1304, 'city_code' => '', 'province_id' => '87', 'province_code' => '', 'city_name' => 'Kabupaten Siak', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1305, 'city_code' => '', 'province_id' => '88', 'province_code' => '', 'city_name' => 'Kabupaten Majene', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1306, 'city_code' => '', 'province_id' => '88', 'province_code' => '', 'city_name' => 'Kabupaten Mamasa', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1307, 'city_code' => '', 'province_id' => '88', 'province_code' => '', 'city_name' => 'Kabupaten Mamuju', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1308, 'city_code' => '', 'province_id' => '88', 'province_code' => '', 'city_name' => 'Kabupaten Mamuju Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1309, 'city_code' => '', 'province_id' => '88', 'province_code' => '', 'city_name' => 'Kabupaten Mamuju Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1310, 'city_code' => '', 'province_id' => '88', 'province_code' => '', 'city_name' => 'Kabupaten Polewali Mandar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1311, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Bantaeng', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1312, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Barru', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1313, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Bone', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1314, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Bulukumba', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1315, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Enrekang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1316, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Gowa', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1317, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Jeneponto', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1318, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Kepulauan Selayar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1319, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Luwu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1320, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Luwu Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1321, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Luwu Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1322, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kota Makassar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1323, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Maros', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1324, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kota Palopo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1325, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Pangkajene Kepulauan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1326, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kota Parepare', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1327, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Pinrang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1328, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Sidenreng Rappang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1329, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Sinjai', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1330, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Soppeng', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1331, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Takalar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1332, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Tana Toraja', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1333, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Toraja Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1334, 'city_code' => '', 'province_id' => '89', 'province_code' => '', 'city_name' => 'Kabupaten Wajo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1335, 'city_code' => '', 'province_id' => '90', 'province_code' => '', 'city_name' => 'Kabupaten Banggai', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1336, 'city_code' => '', 'province_id' => '90', 'province_code' => '', 'city_name' => 'Kabupaten Banggai Kepulauan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1337, 'city_code' => '', 'province_id' => '90', 'province_code' => '', 'city_name' => 'Kabupaten Banggai Laut', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1338, 'city_code' => '', 'province_id' => '90', 'province_code' => '', 'city_name' => 'Kabupaten Buol', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1339, 'city_code' => '', 'province_id' => '90', 'province_code' => '', 'city_name' => 'Kabupaten Donggala', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1340, 'city_code' => '', 'province_id' => '90', 'province_code' => '', 'city_name' => 'Kabupaten Morowali', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1341, 'city_code' => '', 'province_id' => '90', 'province_code' => '', 'city_name' => 'Kabupaten Morowali Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1342, 'city_code' => '', 'province_id' => '90', 'province_code' => '', 'city_name' => 'Kota Palu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1343, 'city_code' => '', 'province_id' => '90', 'province_code' => '', 'city_name' => 'Kabupaten Parigi Moutong', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1344, 'city_code' => '', 'province_id' => '90', 'province_code' => '', 'city_name' => 'Kabupaten Poso', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1345, 'city_code' => '', 'province_id' => '90', 'province_code' => '', 'city_name' => 'Kabupaten Sigi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1346, 'city_code' => '', 'province_id' => '90', 'province_code' => '', 'city_name' => 'Kabupaten Tojo Una-Una', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1347, 'city_code' => '', 'province_id' => '90', 'province_code' => '', 'city_name' => 'Kabupaten Toli-Toli', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1348, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kota Bau-Bau', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1349, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Bombana', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1350, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Buton', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1351, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Buton Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1352, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Buton Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1353, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Buton Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1354, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kota Kendari', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1355, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Kolaka', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1356, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Kolaka Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1357, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Kolaka Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1358, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Konawe', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1359, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Konawe Kepulauan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1360, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Konawe Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1361, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Konawe Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1362, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Muna', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1363, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Muna Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1364, 'city_code' => '', 'province_id' => '91', 'province_code' => '', 'city_name' => 'Kabupaten Wakatobi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1365, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kota Bitung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1366, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kabupaten Bolaang Mongondow', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1367, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kabupaten Bolaang Mongondow Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1368, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kabupaten Bolaang Mongondow Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1369, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kabupaten Bolaang Mongondow Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1370, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kabupaten Kepulauan Sangihe', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1371, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1372, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kabupaten Kepulauan Talaud', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1373, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kota Kotamobagu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1374, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kota Manado', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1375, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kabupaten Minahasa', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1376, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kabupaten Minahasa Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1377, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kabupaten Minahasa Tenggara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1378, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kabupaten Minahasa Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1379, 'city_code' => '', 'province_id' => '92', 'province_code' => '', 'city_name' => 'Kota Tomohon', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1380, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kabupaten Agam', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1381, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kota Bukittinggi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1382, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kabupaten Dharmasraya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1383, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kabupaten Kepulauan Mentawai', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1384, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kabupaten Lima Puluh Kota', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1385, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kota Padang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1386, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kota Padang Panjang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1387, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kabupaten Padang Pariaman', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1388, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kota Pariaman', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1389, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kabupaten Pasaman', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1390, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kabupaten Pasaman Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1391, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kota Payakumbuh', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1392, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kabupaten Pesisir Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1393, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kota Sawah Lunto', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1394, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kabupaten Sijunjung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1395, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kota Solok', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1396, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kabupaten Solok', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1397, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kabupaten Solok Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1398, 'city_code' => '', 'province_id' => '93', 'province_code' => '', 'city_name' => 'Kabupaten Tanah Datar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1399, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kabupaten Banyuasin', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1400, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kabupaten Empat Lawang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1401, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kabupaten Lahat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1402, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kota Lubuk Linggau', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1403, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kabupaten Muara Enim', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1404, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kabupaten Musi Banyuasin', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1405, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kabupaten Musi Rawas', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1406, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kabupaten Musi Rawas Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1407, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kabupaten Ogan Ilir', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1408, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kabupaten Ogan Komering Ilir', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1409, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kabupaten Ogan Komering Ulu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1410, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kabupaten Ogan Komering Ulu Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1411, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kabupaten Ogan Komering Ulu Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1412, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kota Pagar Alam', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1413, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kota Palembang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1414, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kabupaten Penukal Abab Lematang Ilir', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1415, 'city_code' => '', 'province_id' => '94', 'province_code' => '', 'city_name' => 'Kota Prabumulih', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1416, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Asahan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1417, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Batu Bara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1418, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kota Binjai', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1419, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Dairi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1420, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Deli Serdang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1421, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kota Gunungsitoli', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1422, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Humbang Hasundutan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1423, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Karo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1424, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Labuhanbatu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1425, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Labuhanbatu Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1426, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Labuhanbatu Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1427, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Langkat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1428, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Mandailing Natal', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1429, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kota Medan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1430, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Nias', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1431, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Nias Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1432, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Nias Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1433, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Nias Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1434, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Padang Lawas', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1435, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Padang Lawas Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1436, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kota Padang Sidempuan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1437, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Pakpak Bharat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1438, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kota Pematang Siantar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1439, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Samosir', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1440, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Serdang Bedagai', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1441, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kota Sibolga', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1442, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Simalungun', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1443, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kota Tanjung Balai', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1444, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Tapanuli Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1445, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Tapanuli Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1446, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Tapanuli Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1447, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kota Tebing Tinggi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1448, 'city_code' => '', 'province_id' => '95', 'province_code' => '', 'city_name' => 'Kabupaten Toba Samosir', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
        ]);
    }
}
