<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CoreCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('core_city')->insert([
            ['city_id' => 936, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Gianyar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 937, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Bangli', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 938, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Buleleng', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 939, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Tabanan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 940, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Karangasem', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 941, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Badung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 942, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Jembrana', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 943, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Klungkung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 944, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kota Denpasar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 945, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Bangka Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 946, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Bangka Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 947, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Belitung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 948, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kota Pangkal Pinang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 949, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Bangka Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 950, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Bangka', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 951, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Belitung Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 952, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kabupaten Lebak', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 953, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kabupaten Serang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 954, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kota Serang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 955, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kabupaten Tangerang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 956, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kota Tangerang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 957, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kabupaten Pandeglang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 958, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kota Tangerang Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 959, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kota Cilegon', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 960, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Seluma', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 961, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Bengkulu Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 962, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kota Bengkulu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 963, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Muko Muko', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 964, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Rejang Lebong', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 965, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Kaur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 966, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Bengkulu Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 967, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Kepahiang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 968, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Lebong', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 969, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Bengkulu Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 970, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kabupaten Gunung Kidul', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 971, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kota Yogyakarta', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 972, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kabupaten Kulon Progo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 973, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kabupaten Sleman', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 974, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kabupaten Bantul', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 975, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 976, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 977, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Pusat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 978, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 979, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 980, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kabupaten Kepulauan Seribu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 981, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Boalemo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 982, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Pohuwato', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 983, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Gorontalo Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 984, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Gorontalo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 985, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Bone Bolango', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 986, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kota Gorontalo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 987, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Tebo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 988, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Tanjung Jabung Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 989, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Merangin', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 990, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kota Jambi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 991, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Bungo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 992, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kota Sungaipenuh', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 993, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Muaro Jambi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 994, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Kerinci', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 995, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Sarolangun', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 996, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Tanjung Jabung Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 997, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Batang Hari', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 998, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Indramayu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 999, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Cirebon', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1000, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Cianjur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1001, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Sukabumi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1002, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Sukabumi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1003, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Purwakarta', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1004, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Garut', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1005, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Sumedang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1006, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Bandung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1007, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Karawang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1008, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Bogor', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1009, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Tasikmalaya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1010, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Bekasi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1011, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Tasikmalaya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1012, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Depok', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1013, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Subang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1014, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Bogor', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1015, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Ciamis', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1016, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Majalengka', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1017, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Kuningan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1018, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Bandung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1019, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Bandung Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1020, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Pangandaran', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1021, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Bekasi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1022, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Banjar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1023, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Cirebon', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1024, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Cimahi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1025, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Wonogiri', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1026, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Batang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1027, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Wonosobo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1028, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Boyolali', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1029, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Klaten', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1030, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Demak', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1031, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Pekalongan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1032, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Temanggung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1033, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Grobogan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1034, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Pati', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1035, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Magelang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1036, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Sukoharjo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1037, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Kendal', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1038, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Jepara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1039, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Pemalang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1040, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Tegal', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1041, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Banyumas', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1042, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Banjarnegara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1043, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Brebes', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1044, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Cilacap', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1045, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Semarang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1046, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Kudus', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1047, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Blora', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1048, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Semarang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1049, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Salatiga', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1050, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Tegal', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1051, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Karanganyar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1052, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Sragen', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1053, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Rembang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1054, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Kebumen', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1055, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Surakarta', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1056, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Purbalingga', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1057, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Purworejo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1058, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Pekalongan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1059, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Magelang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1060, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Bangkalan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1061, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Banyuwangi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1062, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Batu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1063, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Blitar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
        ]);
    }
}
