<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CoreKecamatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('core_kecamatan')->insert([
            ['kecamatan_id' => 12863, 'city_code' => '', 'city_id' => 936, 'kecamatan_code' => '', 'kecamatan_name' => 'Belah Batuh (Blahbatuh)', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12864, 'city_code' => '', 'city_id' => 936, 'kecamatan_code' => '', 'kecamatan_name' => 'Gianyar', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12865, 'city_code' => '', 'city_id' => 936, 'kecamatan_code' => '', 'kecamatan_name' => 'Payangan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12866, 'city_code' => '', 'city_id' => 936, 'kecamatan_code' => '', 'kecamatan_name' => 'Sukawati', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12867, 'city_code' => '', 'city_id' => 936, 'kecamatan_code' => '', 'kecamatan_name' => 'Tampak Siring', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12868, 'city_code' => '', 'city_id' => 936, 'kecamatan_code' => '', 'kecamatan_name' => 'Tegallalang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12869, 'city_code' => '', 'city_id' => 936, 'kecamatan_code' => '', 'kecamatan_name' => 'Ubud', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12870, 'city_code' => '', 'city_id' => 937, 'kecamatan_code' => '', 'kecamatan_name' => 'Bangli', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12871, 'city_code' => '', 'city_id' => 937, 'kecamatan_code' => '', 'kecamatan_name' => 'Kintamani', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12872, 'city_code' => '', 'city_id' => 937, 'kecamatan_code' => '', 'kecamatan_name' => 'Susut', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12873, 'city_code' => '', 'city_id' => 937, 'kecamatan_code' => '', 'kecamatan_name' => 'Tembuku', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12874, 'city_code' => '', 'city_id' => 938, 'kecamatan_code' => '', 'kecamatan_name' => 'Banjar', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12875, 'city_code' => '', 'city_id' => 938, 'kecamatan_code' => '', 'kecamatan_name' => 'Buleleng', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12876, 'city_code' => '', 'city_id' => 938, 'kecamatan_code' => '', 'kecamatan_name' => 'Busungbiu', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12877, 'city_code' => '', 'city_id' => 938, 'kecamatan_code' => '', 'kecamatan_name' => 'Gerokgak', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12878, 'city_code' => '', 'city_id' => 938, 'kecamatan_code' => '', 'kecamatan_name' => 'Kubutambahan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12879, 'city_code' => '', 'city_id' => 938, 'kecamatan_code' => '', 'kecamatan_name' => 'Sawan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12880, 'city_code' => '', 'city_id' => 938, 'kecamatan_code' => '', 'kecamatan_name' => 'Seririt', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12881, 'city_code' => '', 'city_id' => 938, 'kecamatan_code' => '', 'kecamatan_name' => 'Sukasada', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12882, 'city_code' => '', 'city_id' => 938, 'kecamatan_code' => '', 'kecamatan_name' => 'Tejakula', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12883, 'city_code' => '', 'city_id' => 939, 'kecamatan_code' => '', 'kecamatan_name' => 'Baturiti', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12884, 'city_code' => '', 'city_id' => 939, 'kecamatan_code' => '', 'kecamatan_name' => 'Kediri', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12885, 'city_code' => '', 'city_id' => 939, 'kecamatan_code' => '', 'kecamatan_name' => 'Kerambitan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12886, 'city_code' => '', 'city_id' => 939, 'kecamatan_code' => '', 'kecamatan_name' => 'Marga', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12887, 'city_code' => '', 'city_id' => 939, 'kecamatan_code' => '', 'kecamatan_name' => 'Penebel', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12888, 'city_code' => '', 'city_id' => 939, 'kecamatan_code' => '', 'kecamatan_name' => 'Pupuan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12889, 'city_code' => '', 'city_id' => 939, 'kecamatan_code' => '', 'kecamatan_name' => 'Salemadeg Barat', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12890, 'city_code' => '', 'city_id' => 939, 'kecamatan_code' => '', 'kecamatan_name' => 'Salemadeg Timur', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12891, 'city_code' => '', 'city_id' => 939, 'kecamatan_code' => '', 'kecamatan_name' => 'Selemadeg', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12892, 'city_code' => '', 'city_id' => 939, 'kecamatan_code' => '', 'kecamatan_name' => 'Tabanan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12893, 'city_code' => '', 'city_id' => 940, 'kecamatan_code' => '', 'kecamatan_name' => 'Abang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12894, 'city_code' => '', 'city_id' => 940, 'kecamatan_code' => '', 'kecamatan_name' => 'Bebandem', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12895, 'city_code' => '', 'city_id' => 940, 'kecamatan_code' => '', 'kecamatan_name' => 'Karang Asem', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12896, 'city_code' => '', 'city_id' => 940, 'kecamatan_code' => '', 'kecamatan_name' => 'Kubu', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12897, 'city_code' => '', 'city_id' => 940, 'kecamatan_code' => '', 'kecamatan_name' => 'Manggis', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12898, 'city_code' => '', 'city_id' => 940, 'kecamatan_code' => '', 'kecamatan_name' => 'Rendang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12899, 'city_code' => '', 'city_id' => 940, 'kecamatan_code' => '', 'kecamatan_name' => 'Selat', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12900, 'city_code' => '', 'city_id' => 940, 'kecamatan_code' => '', 'kecamatan_name' => 'Sidemen', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12901, 'city_code' => '', 'city_id' => 941, 'kecamatan_code' => '', 'kecamatan_name' => 'Abiansemal', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12902, 'city_code' => '', 'city_id' => 941, 'kecamatan_code' => '', 'kecamatan_name' => 'Kuta', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12903, 'city_code' => '', 'city_id' => 941, 'kecamatan_code' => '', 'kecamatan_name' => 'Kuta Selatan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12904, 'city_code' => '', 'city_id' => 941, 'kecamatan_code' => '', 'kecamatan_name' => 'Kuta Utara', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12905, 'city_code' => '', 'city_id' => 941, 'kecamatan_code' => '', 'kecamatan_name' => 'Mengwi', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12906, 'city_code' => '', 'city_id' => 941, 'kecamatan_code' => '', 'kecamatan_name' => 'Petang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12907, 'city_code' => '', 'city_id' => 942, 'kecamatan_code' => '', 'kecamatan_name' => 'Jembrana', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12908, 'city_code' => '', 'city_id' => 942, 'kecamatan_code' => '', 'kecamatan_name' => 'Melaya', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12909, 'city_code' => '', 'city_id' => 942, 'kecamatan_code' => '', 'kecamatan_name' => 'Mendoyo', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12910, 'city_code' => '', 'city_id' => 942, 'kecamatan_code' => '', 'kecamatan_name' => 'Negara', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12911, 'city_code' => '', 'city_id' => 942, 'kecamatan_code' => '', 'kecamatan_name' => 'Pekutatan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12912, 'city_code' => '', 'city_id' => 943, 'kecamatan_code' => '', 'kecamatan_name' => 'Banjarangkan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12913, 'city_code' => '', 'city_id' => 943, 'kecamatan_code' => '', 'kecamatan_name' => 'Dawan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12914, 'city_code' => '', 'city_id' => 943, 'kecamatan_code' => '', 'kecamatan_name' => 'Klungkung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12915, 'city_code' => '', 'city_id' => 943, 'kecamatan_code' => '', 'kecamatan_name' => 'Nusapenida', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12916, 'city_code' => '', 'city_id' => 944, 'kecamatan_code' => '', 'kecamatan_name' => 'Denpasar Barat', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12917, 'city_code' => '', 'city_id' => 944, 'kecamatan_code' => '', 'kecamatan_name' => 'Denpasar Selatan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12918, 'city_code' => '', 'city_id' => 944, 'kecamatan_code' => '', 'kecamatan_name' => 'Denpasar Timur', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12919, 'city_code' => '', 'city_id' => 944, 'kecamatan_code' => '', 'kecamatan_name' => 'Denpasar Utara', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12920, 'city_code' => '', 'city_id' => 945, 'kecamatan_code' => '', 'kecamatan_name' => 'Air Gegas', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12921, 'city_code' => '', 'city_id' => 945, 'kecamatan_code' => '', 'kecamatan_name' => 'Kepulauan Pongok', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12922, 'city_code' => '', 'city_id' => 945, 'kecamatan_code' => '', 'kecamatan_name' => 'Lepar Pongok', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12923, 'city_code' => '', 'city_id' => 945, 'kecamatan_code' => '', 'kecamatan_name' => 'Payung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12924, 'city_code' => '', 'city_id' => 945, 'kecamatan_code' => '', 'kecamatan_name' => 'Pulau Besar', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12925, 'city_code' => '', 'city_id' => 945, 'kecamatan_code' => '', 'kecamatan_name' => 'Simpang Rimba', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12926, 'city_code' => '', 'city_id' => 945, 'kecamatan_code' => '', 'kecamatan_name' => 'Toboali', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12927, 'city_code' => '', 'city_id' => 945, 'kecamatan_code' => '', 'kecamatan_name' => 'Tukak Sadai', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12928, 'city_code' => '', 'city_id' => 946, 'kecamatan_code' => '', 'kecamatan_name' => 'Jebus', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12929, 'city_code' => '', 'city_id' => 946, 'kecamatan_code' => '', 'kecamatan_name' => 'Kelapa', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12930, 'city_code' => '', 'city_id' => 946, 'kecamatan_code' => '', 'kecamatan_name' => 'Mentok (Muntok)', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12931, 'city_code' => '', 'city_id' => 946, 'kecamatan_code' => '', 'kecamatan_name' => 'Parittiga', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12932, 'city_code' => '', 'city_id' => 946, 'kecamatan_code' => '', 'kecamatan_name' => 'Simpang Teritip', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12933, 'city_code' => '', 'city_id' => 946, 'kecamatan_code' => '', 'kecamatan_name' => 'Tempilang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12934, 'city_code' => '', 'city_id' => 947, 'kecamatan_code' => '', 'kecamatan_name' => 'Badau', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12935, 'city_code' => '', 'city_id' => 947, 'kecamatan_code' => '', 'kecamatan_name' => 'Membalong', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12936, 'city_code' => '', 'city_id' => 947, 'kecamatan_code' => '', 'kecamatan_name' => 'Selat Nasik', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12937, 'city_code' => '', 'city_id' => 947, 'kecamatan_code' => '', 'kecamatan_name' => 'Sijuk', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12938, 'city_code' => '', 'city_id' => 947, 'kecamatan_code' => '', 'kecamatan_name' => 'Tanjung Pandan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12939, 'city_code' => '', 'city_id' => 948, 'kecamatan_code' => '', 'kecamatan_name' => 'Bukit Intan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12940, 'city_code' => '', 'city_id' => 948, 'kecamatan_code' => '', 'kecamatan_name' => 'Gabek', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12941, 'city_code' => '', 'city_id' => 948, 'kecamatan_code' => '', 'kecamatan_name' => 'Gerunggang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12942, 'city_code' => '', 'city_id' => 948, 'kecamatan_code' => '', 'kecamatan_name' => 'Girimaya', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12943, 'city_code' => '', 'city_id' => 948, 'kecamatan_code' => '', 'kecamatan_name' => 'Pangkal Balam', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12944, 'city_code' => '', 'city_id' => 948, 'kecamatan_code' => '', 'kecamatan_name' => 'Rangkui', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12945, 'city_code' => '', 'city_id' => 948, 'kecamatan_code' => '', 'kecamatan_name' => 'Taman Sari', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12946, 'city_code' => '', 'city_id' => 949, 'kecamatan_code' => '', 'kecamatan_name' => 'Koba', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12947, 'city_code' => '', 'city_id' => 949, 'kecamatan_code' => '', 'kecamatan_name' => 'Lubuk Besar', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12948, 'city_code' => '', 'city_id' => 949, 'kecamatan_code' => '', 'kecamatan_name' => 'Namang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12949, 'city_code' => '', 'city_id' => 949, 'kecamatan_code' => '', 'kecamatan_name' => 'Pangkalan Baru', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12950, 'city_code' => '', 'city_id' => 949, 'kecamatan_code' => '', 'kecamatan_name' => 'Simpang Katis', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12951, 'city_code' => '', 'city_id' => 949, 'kecamatan_code' => '', 'kecamatan_name' => 'Sungai Selan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12952, 'city_code' => '', 'city_id' => 950, 'kecamatan_code' => '', 'kecamatan_name' => 'Bakam', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12953, 'city_code' => '', 'city_id' => 950, 'kecamatan_code' => '', 'kecamatan_name' => 'Belinyu', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12954, 'city_code' => '', 'city_id' => 950, 'kecamatan_code' => '', 'kecamatan_name' => 'Mendo Barat', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12955, 'city_code' => '', 'city_id' => 950, 'kecamatan_code' => '', 'kecamatan_name' => 'Merawang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12956, 'city_code' => '', 'city_id' => 950, 'kecamatan_code' => '', 'kecamatan_name' => 'Pemali', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12957, 'city_code' => '', 'city_id' => 950, 'kecamatan_code' => '', 'kecamatan_name' => 'Puding Besar', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12958, 'city_code' => '', 'city_id' => 950, 'kecamatan_code' => '', 'kecamatan_name' => 'Riau Silip', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12959, 'city_code' => '', 'city_id' => 950, 'kecamatan_code' => '', 'kecamatan_name' => 'Sungai Liat', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12960, 'city_code' => '', 'city_id' => 951, 'kecamatan_code' => '', 'kecamatan_name' => 'Damar', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12961, 'city_code' => '', 'city_id' => 951, 'kecamatan_code' => '', 'kecamatan_name' => 'Dendang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12962, 'city_code' => '', 'city_id' => 951, 'kecamatan_code' => '', 'kecamatan_name' => 'Gantung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12963, 'city_code' => '', 'city_id' => 951, 'kecamatan_code' => '', 'kecamatan_name' => 'Kelapa Kampit', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12964, 'city_code' => '', 'city_id' => 951, 'kecamatan_code' => '', 'kecamatan_name' => 'Manggar', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12965, 'city_code' => '', 'city_id' => 951, 'kecamatan_code' => '', 'kecamatan_name' => 'Simpang Pesak', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12966, 'city_code' => '', 'city_id' => 951, 'kecamatan_code' => '', 'kecamatan_name' => 'Simpang Renggiang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12967, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Banjarsari', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12968, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Bayah', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12969, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Bojongmanik', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12970, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Cibadak', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12971, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Cibeber', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12972, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Cigemblong', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12973, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Cihara', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12974, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Cijaku', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12975, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Cikulur', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12976, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Cileles', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12977, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Cilograng', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12978, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Cimarga', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12979, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Cipanas', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12980, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Cirinten', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12981, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Curugbitung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12982, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Gunung Kencana', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12983, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Kalanganyar', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12984, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Lebakgedong', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12985, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Leuwidamar', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12986, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Maja', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12987, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Malingping', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12988, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Muncang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12989, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Panggarangan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12990, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Rangkasbitung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12991, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Sajira', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12992, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Sobang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12993, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Wanasalam', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12994, 'city_code' => '', 'city_id' => 952, 'kecamatan_code' => '', 'kecamatan_name' => 'Warunggunung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12995, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Anyar', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12996, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Bandung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12997, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Baros', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12998, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Binuang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 12999, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Bojonegara', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13000, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Carenang (Cerenang)', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13001, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Cikande', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13002, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Cikeusal', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13003, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Cinangka', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13004, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Ciomas', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13005, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Ciruas', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13006, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Gunungsari', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13007, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Jawilan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13008, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Kibin', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13009, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Kopo', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13010, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Kragilan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13011, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Kramatwatu', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13012, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Lebak Wangi', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13013, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Mancak', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13014, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Pabuaran', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13015, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Padarincang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13016, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Pamarayan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13017, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Petir', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13018, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Pontang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13019, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Pulo Ampel', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13020, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Tanara', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13021, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Tirtayasa', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13022, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Tunjung Teja', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13023, 'city_code' => '', 'city_id' => 953, 'kecamatan_code' => '', 'kecamatan_name' => 'Waringin Kurung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13024, 'city_code' => '', 'city_id' => 954, 'kecamatan_code' => '', 'kecamatan_name' => 'Cipocok Jaya', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13025, 'city_code' => '', 'city_id' => 954, 'kecamatan_code' => '', 'kecamatan_name' => 'Curug', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13026, 'city_code' => '', 'city_id' => 954, 'kecamatan_code' => '', 'kecamatan_name' => 'Kasemen', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13027, 'city_code' => '', 'city_id' => 954, 'kecamatan_code' => '', 'kecamatan_name' => 'Serang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13028, 'city_code' => '', 'city_id' => 954, 'kecamatan_code' => '', 'kecamatan_name' => 'Taktakan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13029, 'city_code' => '', 'city_id' => 954, 'kecamatan_code' => '', 'kecamatan_name' => 'Walantaka', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13030, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Balaraja', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13031, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Cikupa', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13032, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Cisauk', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13033, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Cisoka', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13034, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Curug', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13035, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Gunung Kaler', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13036, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Jambe', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13037, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Jayanti', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13038, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Kelapa Dua', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13039, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Kemiri', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13040, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Kosambi', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13041, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Kresek', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13042, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Kronjo', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13043, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Legok', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13044, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Mauk', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13045, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Mekar Baru', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13046, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Pagedangan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13047, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Pakuhaji', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13048, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Panongan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13049, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Pasar Kemis', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13050, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Rajeg', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13051, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Sepatan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13052, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Sepatan Timur', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13053, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Sindang Jaya', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13054, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Solear', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13055, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Sukadiri', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13056, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Sukamulya', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13057, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Teluknaga', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13058, 'city_code' => '', 'city_id' => 955, 'kecamatan_code' => '', 'kecamatan_name' => 'Tigaraksa', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13059, 'city_code' => '', 'city_id' => 956, 'kecamatan_code' => '', 'kecamatan_name' => 'Batuceper', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13060, 'city_code' => '', 'city_id' => 956, 'kecamatan_code' => '', 'kecamatan_name' => 'Benda', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13061, 'city_code' => '', 'city_id' => 956, 'kecamatan_code' => '', 'kecamatan_name' => 'Cibodas', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13062, 'city_code' => '', 'city_id' => 956, 'kecamatan_code' => '', 'kecamatan_name' => 'Ciledug', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13063, 'city_code' => '', 'city_id' => 956, 'kecamatan_code' => '', 'kecamatan_name' => 'Cipondoh', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13064, 'city_code' => '', 'city_id' => 956, 'kecamatan_code' => '', 'kecamatan_name' => 'Jatiuwung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13065, 'city_code' => '', 'city_id' => 956, 'kecamatan_code' => '', 'kecamatan_name' => 'Karang Tengah', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13066, 'city_code' => '', 'city_id' => 956, 'kecamatan_code' => '', 'kecamatan_name' => 'Karawaci', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13067, 'city_code' => '', 'city_id' => 956, 'kecamatan_code' => '', 'kecamatan_name' => 'Larangan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13068, 'city_code' => '', 'city_id' => 956, 'kecamatan_code' => '', 'kecamatan_name' => 'Neglasari', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13069, 'city_code' => '', 'city_id' => 956, 'kecamatan_code' => '', 'kecamatan_name' => 'Periuk', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13070, 'city_code' => '', 'city_id' => 956, 'kecamatan_code' => '', 'kecamatan_name' => 'Pinang (Penang)', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13071, 'city_code' => '', 'city_id' => 956, 'kecamatan_code' => '', 'kecamatan_name' => 'Tangerang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13072, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Angsana', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13073, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Banjar', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13074, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Bojong', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13075, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Cadasari', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13076, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Carita', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13077, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Cibaliung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13078, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Cibitung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13079, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Cigeulis', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13080, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Cikeudal (Cikedal)', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13081, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Cikeusik', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13082, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Cimanggu', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13083, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Cimanuk', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13084, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Cipeucang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13085, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Cisata', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13086, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Jiput', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13087, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Kaduhejo', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13088, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Karang Tanjung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13089, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Koroncong', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13090, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Labuan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13091, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Majasari', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13092, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Mandalawangi', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13093, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Mekarjaya', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13094, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Menes', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13095, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Munjul', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13096, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Pagelaran', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13097, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Pandeglang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13098, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Panimbang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13099, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Patia', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13100, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Picung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13101, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Pulosari', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13102, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Saketi', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13103, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Sindangresmi', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13104, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Sobang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13105, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Sukaresmi', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13106, 'city_code' => '', 'city_id' => 957, 'kecamatan_code' => '', 'kecamatan_name' => 'Sumur', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13107, 'city_code' => '', 'city_id' => 958, 'kecamatan_code' => '', 'kecamatan_name' => 'Ciputat', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13108, 'city_code' => '', 'city_id' => 958, 'kecamatan_code' => '', 'kecamatan_name' => 'Ciputat Timur', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13109, 'city_code' => '', 'city_id' => 958, 'kecamatan_code' => '', 'kecamatan_name' => 'Pamulang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13110, 'city_code' => '', 'city_id' => 958, 'kecamatan_code' => '', 'kecamatan_name' => 'Pondok Aren', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13111, 'city_code' => '', 'city_id' => 958, 'kecamatan_code' => '', 'kecamatan_name' => 'Serpong', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13112, 'city_code' => '', 'city_id' => 958, 'kecamatan_code' => '', 'kecamatan_name' => 'Serpong Utara', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13113, 'city_code' => '', 'city_id' => 958, 'kecamatan_code' => '', 'kecamatan_name' => 'Setu', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13114, 'city_code' => '', 'city_id' => 959, 'kecamatan_code' => '', 'kecamatan_name' => 'Cibeber', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13115, 'city_code' => '', 'city_id' => 959, 'kecamatan_code' => '', 'kecamatan_name' => 'Cilegon', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13116, 'city_code' => '', 'city_id' => 959, 'kecamatan_code' => '', 'kecamatan_name' => 'Citangkil', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13117, 'city_code' => '', 'city_id' => 959, 'kecamatan_code' => '', 'kecamatan_name' => 'Ciwandan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13118, 'city_code' => '', 'city_id' => 959, 'kecamatan_code' => '', 'kecamatan_name' => 'Gerogol', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13119, 'city_code' => '', 'city_id' => 959, 'kecamatan_code' => '', 'kecamatan_name' => 'Jombang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13120, 'city_code' => '', 'city_id' => 959, 'kecamatan_code' => '', 'kecamatan_name' => 'Pulomerak', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13121, 'city_code' => '', 'city_id' => 959, 'kecamatan_code' => '', 'kecamatan_name' => 'Purwakarta', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13122, 'city_code' => '', 'city_id' => 960, 'kecamatan_code' => '', 'kecamatan_name' => 'Air Periukan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13123, 'city_code' => '', 'city_id' => 960, 'kecamatan_code' => '', 'kecamatan_name' => 'Ilir Talo', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13124, 'city_code' => '', 'city_id' => 960, 'kecamatan_code' => '', 'kecamatan_name' => 'Lubuk Sandi', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13125, 'city_code' => '', 'city_id' => 960, 'kecamatan_code' => '', 'kecamatan_name' => 'Seluma', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13126, 'city_code' => '', 'city_id' => 960, 'kecamatan_code' => '', 'kecamatan_name' => 'Seluma Barat', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13127, 'city_code' => '', 'city_id' => 960, 'kecamatan_code' => '', 'kecamatan_name' => 'Seluma Selatan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13128, 'city_code' => '', 'city_id' => 960, 'kecamatan_code' => '', 'kecamatan_name' => 'Seluma Timur', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13129, 'city_code' => '', 'city_id' => 960, 'kecamatan_code' => '', 'kecamatan_name' => 'Seluma Utara', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13130, 'city_code' => '', 'city_id' => 960, 'kecamatan_code' => '', 'kecamatan_name' => 'Semidang Alas', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13131, 'city_code' => '', 'city_id' => 960, 'kecamatan_code' => '', 'kecamatan_name' => 'Semidang Alas Maras', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13132, 'city_code' => '', 'city_id' => 960, 'kecamatan_code' => '', 'kecamatan_name' => 'Sukaraja', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13133, 'city_code' => '', 'city_id' => 960, 'kecamatan_code' => '', 'kecamatan_name' => 'Talo', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13134, 'city_code' => '', 'city_id' => 961, 'kecamatan_code' => '', 'kecamatan_name' => 'Bang Haji', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13135, 'city_code' => '', 'city_id' => 961, 'kecamatan_code' => '', 'kecamatan_name' => 'Karang Tinggi', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13136, 'city_code' => '', 'city_id' => 961, 'kecamatan_code' => '', 'kecamatan_name' => 'Merigi Kelindang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13137, 'city_code' => '', 'city_id' => 961, 'kecamatan_code' => '', 'kecamatan_name' => 'Merigi Sakti', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13138, 'city_code' => '', 'city_id' => 961, 'kecamatan_code' => '', 'kecamatan_name' => 'Pagar Jati', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13139, 'city_code' => '', 'city_id' => 961, 'kecamatan_code' => '', 'kecamatan_name' => 'Pematang Tiga', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13140, 'city_code' => '', 'city_id' => 961, 'kecamatan_code' => '', 'kecamatan_name' => 'Pondok Kelapa', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13141, 'city_code' => '', 'city_id' => 961, 'kecamatan_code' => '', 'kecamatan_name' => 'Pondok Kubang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13142, 'city_code' => '', 'city_id' => 961, 'kecamatan_code' => '', 'kecamatan_name' => 'Taba Penanjung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13143, 'city_code' => '', 'city_id' => 961, 'kecamatan_code' => '', 'kecamatan_name' => 'Talang Empat', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13144, 'city_code' => '', 'city_id' => 962, 'kecamatan_code' => '', 'kecamatan_name' => 'Gading Cempaka', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13145, 'city_code' => '', 'city_id' => 962, 'kecamatan_code' => '', 'kecamatan_name' => 'Kampung Melayu', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13146, 'city_code' => '', 'city_id' => 962, 'kecamatan_code' => '', 'kecamatan_name' => 'Muara Bangka Hulu', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13147, 'city_code' => '', 'city_id' => 962, 'kecamatan_code' => '', 'kecamatan_name' => 'Ratu Agung', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13148, 'city_code' => '', 'city_id' => 962, 'kecamatan_code' => '', 'kecamatan_name' => 'Ratu Samban', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13149, 'city_code' => '', 'city_id' => 962, 'kecamatan_code' => '', 'kecamatan_name' => 'Selebar', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13150, 'city_code' => '', 'city_id' => 962, 'kecamatan_code' => '', 'kecamatan_name' => 'Singaran Pati', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13151, 'city_code' => '', 'city_id' => 962, 'kecamatan_code' => '', 'kecamatan_name' => 'Sungai Serut', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13152, 'city_code' => '', 'city_id' => 963, 'kecamatan_code' => '', 'kecamatan_name' => 'Air Dikit', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13153, 'city_code' => '', 'city_id' => 963, 'kecamatan_code' => '', 'kecamatan_name' => 'Air Majunto', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13154, 'city_code' => '', 'city_id' => 963, 'kecamatan_code' => '', 'kecamatan_name' => 'Air Rami', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13155, 'city_code' => '', 'city_id' => 963, 'kecamatan_code' => '', 'kecamatan_name' => 'Ipuh (Muko-Muko Selatan)', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13156, 'city_code' => '', 'city_id' => 963, 'kecamatan_code' => '', 'kecamatan_name' => 'Kota Mukomuko (Mukomuko Utara)', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13157, 'city_code' => '', 'city_id' => 963, 'kecamatan_code' => '', 'kecamatan_name' => 'Lubuk Pinang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13158, 'city_code' => '', 'city_id' => 963, 'kecamatan_code' => '', 'kecamatan_name' => 'Malin Deman', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13159, 'city_code' => '', 'city_id' => 963, 'kecamatan_code' => '', 'kecamatan_name' => 'Penarik', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13160, 'city_code' => '', 'city_id' => 963, 'kecamatan_code' => '', 'kecamatan_name' => 'Pondok Suguh', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13161, 'city_code' => '', 'city_id' => 963, 'kecamatan_code' => '', 'kecamatan_name' => 'Selagan Raya', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13162, 'city_code' => '', 'city_id' => 963, 'kecamatan_code' => '', 'kecamatan_name' => 'Sungai Rumbai', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13163, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Bermani Ulu', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13164, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Bermani Ulu Raya', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13165, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Binduriang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13166, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Curup', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13167, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Curup Selatan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13168, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Curup Tengah', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13169, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Curup Timur', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13170, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Curup Utara', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13171, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Kota Padang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13172, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Padang Ulak Tanding', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13173, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Selupu Rejang', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13174, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Sindang Beliti Ilir', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13175, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Sindang Beliti Ulu', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13176, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Sindang Daratan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13177, 'city_code' => '', 'city_id' => 964, 'kecamatan_code' => '', 'kecamatan_name' => 'Sindang Kelingi', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13178, 'city_code' => '', 'city_id' => 965, 'kecamatan_code' => '', 'kecamatan_name' => 'Kaur Selatan', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13179, 'city_code' => '', 'city_id' => 965, 'kecamatan_code' => '', 'kecamatan_name' => 'Kaur Tengah', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
            ['kecamatan_id' => 13180, 'city_code' => '', 'city_id' => 965, 'kecamatan_code' => '', 'kecamatan_name' => 'Kaur Utara', 'city_no' => '', 'kecamatan_no' => '', 'data_state' => 0],
        ]);
    }
}
