<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CoreKelurahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('core_kelurahan')->insert([
        ['kelurahan_id' => 283362, 'kelurahan_code' => '', 'kecamatan_id' => 12863, 'kecamatan_code' => '', 'kelurahan_name' => 'Bedulu', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283363, 'kelurahan_code' => '', 'kecamatan_id' => 12863, 'kecamatan_code' => '', 'kelurahan_name' => 'Belega', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283364, 'kelurahan_code' => '', 'kecamatan_id' => 12863, 'kecamatan_code' => '', 'kelurahan_name' => 'Blahbatuh', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283365, 'kelurahan_code' => '', 'kecamatan_id' => 12863, 'kecamatan_code' => '', 'kelurahan_name' => 'Bona', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283366, 'kelurahan_code' => '', 'kecamatan_id' => 12863, 'kecamatan_code' => '', 'kelurahan_name' => 'Buruan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283367, 'kelurahan_code' => '', 'kecamatan_id' => 12863, 'kecamatan_code' => '', 'kelurahan_name' => 'Keramas', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283368, 'kelurahan_code' => '', 'kecamatan_id' => 12863, 'kecamatan_code' => '', 'kelurahan_name' => 'Medahan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283369, 'kelurahan_code' => '', 'kecamatan_id' => 12863, 'kecamatan_code' => '', 'kelurahan_name' => 'Pering', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283370, 'kelurahan_code' => '', 'kecamatan_id' => 12863, 'kecamatan_code' => '', 'kelurahan_name' => 'Saba', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283371, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Abianbase', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283372, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Bakbakan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283373, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Beng', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283374, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Bitera', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283375, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Gianyar', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283376, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Lebih', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283377, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Petak', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283378, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Petak Kaja', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283379, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Samplangan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283380, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Serongga', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283381, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Siangan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283382, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Sidan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283383, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Sumita', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283384, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Suwat', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283385, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Tegal Tugu', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283386, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Temesi', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283387, 'kelurahan_code' => '', 'kecamatan_id' => 12864, 'kecamatan_code' => '', 'kelurahan_name' => 'Tulikup', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283388, 'kelurahan_code' => '', 'kecamatan_id' => 12865, 'kecamatan_code' => '', 'kelurahan_name' => 'Bresela (Beresela)', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283389, 'kelurahan_code' => '', 'kecamatan_id' => 12865, 'kecamatan_code' => '', 'kelurahan_name' => 'Buahan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283390, 'kelurahan_code' => '', 'kecamatan_id' => 12865, 'kecamatan_code' => '', 'kelurahan_name' => 'Buahan Kaja', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283391, 'kelurahan_code' => '', 'kecamatan_id' => 12865, 'kecamatan_code' => '', 'kelurahan_name' => 'Bukian', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283392, 'kelurahan_code' => '', 'kecamatan_id' => 12865, 'kecamatan_code' => '', 'kelurahan_name' => 'Kelusa', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283393, 'kelurahan_code' => '', 'kecamatan_id' => 12865, 'kecamatan_code' => '', 'kelurahan_name' => 'Kerta', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283394, 'kelurahan_code' => '', 'kecamatan_id' => 12865, 'kecamatan_code' => '', 'kelurahan_name' => 'Melinggih', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283395, 'kelurahan_code' => '', 'kecamatan_id' => 12865, 'kecamatan_code' => '', 'kelurahan_name' => 'Melinggih Kelod', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283396, 'kelurahan_code' => '', 'kecamatan_id' => 12865, 'kecamatan_code' => '', 'kelurahan_name' => 'Puhu', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283397, 'kelurahan_code' => '', 'kecamatan_id' => 12866, 'kecamatan_code' => '', 'kelurahan_name' => 'Batuan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283398, 'kelurahan_code' => '', 'kecamatan_id' => 12866, 'kecamatan_code' => '', 'kelurahan_name' => 'Batuan Kaler', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283399, 'kelurahan_code' => '', 'kecamatan_id' => 12866, 'kecamatan_code' => '', 'kelurahan_name' => 'Batubulan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283400, 'kelurahan_code' => '', 'kecamatan_id' => 12866, 'kecamatan_code' => '', 'kelurahan_name' => 'Batubulan Kangin', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283401, 'kelurahan_code' => '', 'kecamatan_id' => 12866, 'kecamatan_code' => '', 'kelurahan_name' => 'Celuk', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283402, 'kelurahan_code' => '', 'kecamatan_id' => 12866, 'kecamatan_code' => '', 'kelurahan_name' => 'Guwang', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283403, 'kelurahan_code' => '', 'kecamatan_id' => 12866, 'kecamatan_code' => '', 'kelurahan_name' => 'Kemenuh', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283404, 'kelurahan_code' => '', 'kecamatan_id' => 12866, 'kecamatan_code' => '', 'kelurahan_name' => 'Ketewel', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283405, 'kelurahan_code' => '', 'kecamatan_id' => 12866, 'kecamatan_code' => '', 'kelurahan_name' => 'Singapadu', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283406, 'kelurahan_code' => '', 'kecamatan_id' => 12866, 'kecamatan_code' => '', 'kelurahan_name' => 'Singapadu Kaler', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283407, 'kelurahan_code' => '', 'kecamatan_id' => 12866, 'kecamatan_code' => '', 'kelurahan_name' => 'Singapadu Tengah', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283408, 'kelurahan_code' => '', 'kecamatan_id' => 12866, 'kecamatan_code' => '', 'kelurahan_name' => 'Sukawati', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283409, 'kelurahan_code' => '', 'kecamatan_id' => 12867, 'kecamatan_code' => '', 'kelurahan_name' => 'Manukaya', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283410, 'kelurahan_code' => '', 'kecamatan_id' => 12867, 'kecamatan_code' => '', 'kelurahan_name' => 'Pejeng', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283411, 'kelurahan_code' => '', 'kecamatan_id' => 12867, 'kecamatan_code' => '', 'kelurahan_name' => 'Pejeng Kaja', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283412, 'kelurahan_code' => '', 'kecamatan_id' => 12867, 'kecamatan_code' => '', 'kelurahan_name' => 'Pejeng Kangin', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283413, 'kelurahan_code' => '', 'kecamatan_id' => 12867, 'kecamatan_code' => '', 'kelurahan_name' => 'Pejeng Kawan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283414, 'kelurahan_code' => '', 'kecamatan_id' => 12867, 'kecamatan_code' => '', 'kelurahan_name' => 'Pejeng Klod (Kelod)', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283415, 'kelurahan_code' => '', 'kecamatan_id' => 12867, 'kecamatan_code' => '', 'kelurahan_name' => 'Sanding', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283416, 'kelurahan_code' => '', 'kecamatan_id' => 12867, 'kecamatan_code' => '', 'kelurahan_name' => 'Tampaksiring', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283417, 'kelurahan_code' => '', 'kecamatan_id' => 12868, 'kecamatan_code' => '', 'kelurahan_name' => 'Kedisan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283418, 'kelurahan_code' => '', 'kecamatan_id' => 12868, 'kecamatan_code' => '', 'kelurahan_name' => 'Keliki', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283419, 'kelurahan_code' => '', 'kecamatan_id' => 12868, 'kecamatan_code' => '', 'kelurahan_name' => 'Kenderan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283420, 'kelurahan_code' => '', 'kecamatan_id' => 12868, 'kecamatan_code' => '', 'kelurahan_name' => 'Pupuan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283421, 'kelurahan_code' => '', 'kecamatan_id' => 12868, 'kecamatan_code' => '', 'kelurahan_name' => 'Sebatu', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283422, 'kelurahan_code' => '', 'kecamatan_id' => 12868, 'kecamatan_code' => '', 'kelurahan_name' => 'Taro', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283423, 'kelurahan_code' => '', 'kecamatan_id' => 12868, 'kecamatan_code' => '', 'kelurahan_name' => 'Tegallalang', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283424, 'kelurahan_code' => '', 'kecamatan_id' => 12869, 'kecamatan_code' => '', 'kelurahan_name' => 'Kedewatan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283425, 'kelurahan_code' => '', 'kecamatan_id' => 12869, 'kecamatan_code' => '', 'kelurahan_name' => 'Lodtunduh', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283426, 'kelurahan_code' => '', 'kecamatan_id' => 12869, 'kecamatan_code' => '', 'kelurahan_name' => 'Mas', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283427, 'kelurahan_code' => '', 'kecamatan_id' => 12869, 'kecamatan_code' => '', 'kelurahan_name' => 'Peliatan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283428, 'kelurahan_code' => '', 'kecamatan_id' => 12869, 'kecamatan_code' => '', 'kelurahan_name' => 'Petulu', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283429, 'kelurahan_code' => '', 'kecamatan_id' => 12869, 'kecamatan_code' => '', 'kelurahan_name' => 'Sayan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283430, 'kelurahan_code' => '', 'kecamatan_id' => 12869, 'kecamatan_code' => '', 'kelurahan_name' => 'Singakerta (Singekerta)', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283431, 'kelurahan_code' => '', 'kecamatan_id' => 12869, 'kecamatan_code' => '', 'kelurahan_name' => 'Ubud', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283432, 'kelurahan_code' => '', 'kecamatan_id' => 12870, 'kecamatan_code' => '', 'kelurahan_name' => 'Bebalang', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283433, 'kelurahan_code' => '', 'kecamatan_id' => 12870, 'kecamatan_code' => '', 'kelurahan_name' => 'Bunutin', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283434, 'kelurahan_code' => '', 'kecamatan_id' => 12870, 'kecamatan_code' => '', 'kelurahan_name' => 'Cempaga', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283435, 'kelurahan_code' => '', 'kecamatan_id' => 12870, 'kecamatan_code' => '', 'kelurahan_name' => 'Kawan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283436, 'kelurahan_code' => '', 'kecamatan_id' => 12870, 'kecamatan_code' => '', 'kelurahan_name' => 'Kayubihi', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283437, 'kelurahan_code' => '', 'kecamatan_id' => 12870, 'kecamatan_code' => '', 'kelurahan_name' => 'Kubu', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283438, 'kelurahan_code' => '', 'kecamatan_id' => 12870, 'kecamatan_code' => '', 'kelurahan_name' => 'Landih', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283439, 'kelurahan_code' => '', 'kecamatan_id' => 12870, 'kecamatan_code' => '', 'kelurahan_name' => 'Pengotan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283440, 'kelurahan_code' => '', 'kecamatan_id' => 12870, 'kecamatan_code' => '', 'kelurahan_name' => 'Taman Bali', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283441, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Abang Songan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283442, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Abuan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283443, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Awan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283444, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Bantang', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283445, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Banua', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283446, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Batu Dinding', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283447, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Batukaang', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283448, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Batur Selatan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283449, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Batur Tengah', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283450, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Batur Utara', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283451, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Bayungcerik', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283452, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Bayunggede', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283453, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Belancan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283454, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Belandingan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283455, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Belanga', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283456, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Belantih', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283457, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Binyan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283458, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Bonyoh', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283459, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Buahan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283460, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Bunutin', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283461, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Catur', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283462, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Daup', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283463, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Dausa', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283464, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Gunungbau', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283465, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Katung', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283466, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Kedisan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283467, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Kintamani', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283468, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Kutuh', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283469, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Langgahan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283470, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Lembean', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283471, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Mangguh', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283472, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Manikliyu', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283473, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Mengani', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283474, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Pengejaran', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283475, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Pinggan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283476, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Satra', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283477, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Sekaan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283478, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Sekardadi', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283479, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Selulung', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283480, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Serahi', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283481, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Siyakin', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283482, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Songan A', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283483, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Songan B', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283484, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Subaya', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283485, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Sukawana', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283486, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Suter', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283487, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Terunyan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283488, 'kelurahan_code' => '', 'kecamatan_id' => 12871, 'kecamatan_code' => '', 'kelurahan_name' => 'Ulian', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283489, 'kelurahan_code' => '', 'kecamatan_id' => 12872, 'kecamatan_code' => '', 'kelurahan_name' => 'Abuan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283490, 'kelurahan_code' => '', 'kecamatan_id' => 12872, 'kecamatan_code' => '', 'kelurahan_name' => 'Apuan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283491, 'kelurahan_code' => '', 'kecamatan_id' => 12872, 'kecamatan_code' => '', 'kelurahan_name' => 'Demulih', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283492, 'kelurahan_code' => '', 'kecamatan_id' => 12872, 'kecamatan_code' => '', 'kelurahan_name' => 'Pengiangan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283493, 'kelurahan_code' => '', 'kecamatan_id' => 12872, 'kecamatan_code' => '', 'kelurahan_name' => 'Penglumbaran', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283494, 'kelurahan_code' => '', 'kecamatan_id' => 12872, 'kecamatan_code' => '', 'kelurahan_name' => 'Selat', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283495, 'kelurahan_code' => '', 'kecamatan_id' => 12872, 'kecamatan_code' => '', 'kelurahan_name' => 'Sulahan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283496, 'kelurahan_code' => '', 'kecamatan_id' => 12872, 'kecamatan_code' => '', 'kelurahan_name' => 'Susut', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283497, 'kelurahan_code' => '', 'kecamatan_id' => 12872, 'kecamatan_code' => '', 'kelurahan_name' => 'Tiga', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283498, 'kelurahan_code' => '', 'kecamatan_id' => 12873, 'kecamatan_code' => '', 'kelurahan_name' => 'Bangbang', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283499, 'kelurahan_code' => '', 'kecamatan_id' => 12873, 'kecamatan_code' => '', 'kelurahan_name' => 'Jehem', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283500, 'kelurahan_code' => '', 'kecamatan_id' => 12873, 'kecamatan_code' => '', 'kelurahan_name' => 'Peninjoan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283501, 'kelurahan_code' => '', 'kecamatan_id' => 12873, 'kecamatan_code' => '', 'kelurahan_name' => 'Tembuku', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283502, 'kelurahan_code' => '', 'kecamatan_id' => 12873, 'kecamatan_code' => '', 'kelurahan_name' => 'Undisan', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283503, 'kelurahan_code' => '', 'kecamatan_id' => 12873, 'kecamatan_code' => '', 'kelurahan_name' => 'Yangapi', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283504, 'kelurahan_code' => '', 'kecamatan_id' => 12874, 'kecamatan_code' => '', 'kelurahan_name' => 'Banjar', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283505, 'kelurahan_code' => '', 'kecamatan_id' => 12874, 'kecamatan_code' => '', 'kelurahan_name' => 'Banjar Tegeha', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283506, 'kelurahan_code' => '', 'kecamatan_id' => 12874, 'kecamatan_code' => '', 'kelurahan_name' => 'Banyuatis', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283507, 'kelurahan_code' => '', 'kecamatan_id' => 12874, 'kecamatan_code' => '', 'kelurahan_name' => 'Banyusri', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283508, 'kelurahan_code' => '', 'kecamatan_id' => 12874, 'kecamatan_code' => '', 'kelurahan_name' => 'Cempaga', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
        ['kelurahan_id' => 283509, 'kelurahan_code' => '', 'kecamatan_id' => 12874, 'kecamatan_code' => '', 'kelurahan_name' => 'Dencarik', 'kecamatan_no' => '', 'kelurahan_no' => '', 'data_state' => 0],
    ]);
    }
}
