<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CoreCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('core_city')->insert([
            ['city_id' => 936, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Gianyar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 937, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Bangli', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 938, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Buleleng', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 939, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Tabanan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 940, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Karangasem', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 941, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Badung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 942, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Jembrana', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 943, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kabupaten Klungkung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 944, 'city_code' => '', 'province_id' => '62', 'province_code' => '', 'city_name' => 'Kota Denpasar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 945, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Bangka Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 946, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Bangka Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 947, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Belitung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 948, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kota Pangkal Pinang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 949, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Bangka Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 950, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Bangka', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 951, 'city_code' => '', 'province_id' => '63', 'province_code' => '', 'city_name' => 'Kabupaten Belitung Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 952, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kabupaten Lebak', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 953, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kabupaten Serang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 954, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kota Serang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 955, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kabupaten Tangerang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 956, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kota Tangerang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 957, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kabupaten Pandeglang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 958, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kota Tangerang Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 959, 'city_code' => '', 'province_id' => '64', 'province_code' => '', 'city_name' => 'Kota Cilegon', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 960, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Seluma', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 961, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Bengkulu Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 962, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kota Bengkulu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 963, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Muko Muko', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 964, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Rejang Lebong', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 965, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Kaur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 966, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Bengkulu Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 967, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Kepahiang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 968, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Lebong', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 969, 'city_code' => '', 'province_id' => '65', 'province_code' => '', 'city_name' => 'Kabupaten Bengkulu Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 970, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kabupaten Gunung Kidul', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 971, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kota Yogyakarta', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 972, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kabupaten Kulon Progo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 973, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kabupaten Sleman', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 974, 'city_code' => '', 'province_id' => '66', 'province_code' => '', 'city_name' => 'Kabupaten Bantul', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 975, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 976, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 977, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Pusat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 978, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 979, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kota Jakarta Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 980, 'city_code' => '', 'province_id' => '67', 'province_code' => '', 'city_name' => 'Kabupaten Kepulauan Seribu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 981, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Boalemo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 982, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Pohuwato', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 983, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Gorontalo Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 984, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Gorontalo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 985, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kabupaten Bone Bolango', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 986, 'city_code' => '', 'province_id' => '68', 'province_code' => '', 'city_name' => 'Kota Gorontalo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 987, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Tebo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 988, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Tanjung Jabung Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 989, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Merangin', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 990, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kota Jambi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 991, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Bungo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 992, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kota Sungaipenuh', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 993, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Muaro Jambi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 994, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Kerinci', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 995, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Sarolangun', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 996, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Tanjung Jabung Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 997, 'city_code' => '', 'province_id' => '69', 'province_code' => '', 'city_name' => 'Kabupaten Batang Hari', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 998, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Indramayu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 999, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Cirebon', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1000, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Cianjur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1001, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Sukabumi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1002, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Sukabumi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1003, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Purwakarta', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1004, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Garut', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1005, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Sumedang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1006, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Bandung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1007, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Karawang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1008, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Bogor', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1009, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Tasikmalaya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1010, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Bekasi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1011, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Tasikmalaya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1012, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Depok', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1013, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Subang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1014, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Bogor', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1015, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Ciamis', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1016, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Majalengka', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1017, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Kuningan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1018, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Bandung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1019, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Bandung Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1020, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kabupaten Pangandaran', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1021, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Bekasi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1022, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Banjar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1023, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Cirebon', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1024, 'city_code' => '', 'province_id' => '70', 'province_code' => '', 'city_name' => 'Kota Cimahi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1025, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Wonogiri', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1026, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Batang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1027, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Wonosobo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1028, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Boyolali', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1029, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Klaten', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1030, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Demak', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1031, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Pekalongan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1032, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Temanggung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1033, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Grobogan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1034, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Pati', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1035, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Magelang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1036, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Sukoharjo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1037, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Kendal', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1038, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Jepara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1039, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Pemalang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1040, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Tegal', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1041, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Banyumas', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1042, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Banjarnegara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1043, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Brebes', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1044, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Cilacap', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1045, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Semarang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1046, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Kudus', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1047, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Blora', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1048, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Semarang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1049, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Salatiga', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1050, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Tegal', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1051, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Karanganyar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1052, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Sragen', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1053, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Rembang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1054, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Kebumen', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1055, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Surakarta', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1056, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Purbalingga', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1057, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kabupaten Purworejo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1058, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Pekalongan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1059, 'city_code' => '', 'province_id' => '71', 'province_code' => '', 'city_name' => 'Kota Magelang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1060, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Bangkalan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1061, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Banyuwangi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1062, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Batu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1063, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Blitar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1064, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Blitar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1065, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Bojonegoro', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1066, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Bondowoso', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1067, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Gresik', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1068, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Jember', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1069, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Jombang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1070, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Kediri', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1071, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Kediri', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1072, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Lamongan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1073, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Lumajang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1074, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Madiun', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1075, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Madiun', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1076, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Magetan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1077, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Malang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1078, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Malang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1079, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Mojokerto', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1080, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Mojokerto', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1081, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Nganjuk', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1082, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Ngawi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1083, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Pacitan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1084, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Pamekasan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1085, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Pasuruan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1086, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Pasuruan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1087, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Ponorogo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1088, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Probolinggo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1089, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Probolinggo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1090, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Sampang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1091, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Sidoarjo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1092, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Situbondo', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1093, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Sumenep', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1094, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kota Surabaya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1095, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Trenggalek', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1096, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Tuban', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1097, 'city_code' => '', 'province_id' => '72', 'province_code' => '', 'city_name' => 'Kabupaten Tulungagung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1098, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Bengkayang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1099, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Kapuas Hulu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1100, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Kayong Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1101, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Ketapang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1102, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Kubu Raya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1103, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Landak', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1104, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Melawi', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1105, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Mempawah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1106, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kota Pontianak', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1107, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Sambas', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1108, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Sanggau', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1109, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Sekadau', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1110, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kota Singkawang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1111, 'city_code' => '', 'province_id' => '73', 'province_code' => '', 'city_name' => 'Kabupaten Sintang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1112, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Balangan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1113, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Banjar', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1114, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kota Banjarbaru', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1115, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kota Banjarmasin', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1116, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Barito Kuala', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1117, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Hulu Sungai Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1118, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Hulu Sungai Tengah', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1119, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Hulu Sungai Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1120, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Kotabaru', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1121, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Tabalong', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1122, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Tanah Bumbu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1123, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Tanah Laut', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1124, 'city_code' => '', 'province_id' => '74', 'province_code' => '', 'city_name' => 'Kabupaten Tapin', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1125, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Barito Selatan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1126, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Barito Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1127, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Barito Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1128, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Gunung Mas', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1129, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Kapuas', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1130, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Katingan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1131, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Kotawaringin Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1132, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Kotawaringin Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1133, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Lamandau', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1134, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Murung Raya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1135, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kota Palangka Raya', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1136, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Pulang Pisau', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1137, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Seruyan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1138, 'city_code' => '', 'province_id' => '75', 'province_code' => '', 'city_name' => 'Kabupaten Sukamara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1139, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kota Balikpapan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1140, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kabupaten Berau', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1141, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kota Bontang', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1142, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kabupaten Kutai Barat', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1143, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kabupaten Kutai Kartanegara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1144, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kabupaten Kutai Timur', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1145, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kabupaten Mahakam Ulu', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1146, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kabupaten Paser', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1147, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kabupaten Penajam Paser Utara', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1148, 'city_code' => '', 'province_id' => '76', 'province_code' => '', 'city_name' => 'Kota Samarinda', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1149, 'city_code' => '', 'province_id' => '77', 'province_code' => '', 'city_name' => 'Kabupaten Bulungan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1150, 'city_code' => '', 'province_id' => '77', 'province_code' => '', 'city_name' => 'Kabupaten Malinau', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1151, 'city_code' => '', 'province_id' => '77', 'province_code' => '', 'city_name' => 'Kabupaten Nunukan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1152, 'city_code' => '', 'province_id' => '77', 'province_code' => '', 'city_name' => 'Kabupaten Tana Tidung', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1153, 'city_code' => '', 'province_id' => '77', 'province_code' => '', 'city_name' => 'Kota Tarakan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1154, 'city_code' => '', 'province_id' => '78', 'province_code' => '', 'city_name' => 'Kota Batam', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1155, 'city_code' => '', 'province_id' => '78', 'province_code' => '', 'city_name' => 'Kabupaten Bintan', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1156, 'city_code' => '', 'province_id' => '78', 'province_code' => '', 'city_name' => 'Kabupaten Karimun', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1157, 'city_code' => '', 'province_id' => '78', 'province_code' => '', 'city_name' => 'Kabupaten Kepulauan Anambas', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1158, 'city_code' => '', 'province_id' => '78', 'province_code' => '', 'city_name' => 'Kabupaten Lingga', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
            ['city_id' => 1159, 'city_code' => '', 'province_id' => '78', 'province_code' => '', 'city_name' => 'Kabupaten Natuna', 'province_no' => '', 'city_no' => '', 'data_state' => 0],
        ]);
    }
}
